/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comenzales;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author
 */

public class Interfaz extends javax.swing.JFrame {

    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Edito * WARNING: Do NOT modify this code. The
     * content of this method is always r.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        butFil1 = new javax.swing.JButton();
        labTen1 = new javax.swing.JLabel();
        labTen5 = new javax.swing.JLabel();
        labTen3 = new javax.swing.JLabel();
        butFil2 = new javax.swing.JButton();
        labTen2 = new javax.swing.JLabel();
        labTen4 = new javax.swing.JLabel();
        butFil3 = new javax.swing.JButton();
        butFil4 = new javax.swing.JButton();
        butFil5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butFil1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butFil1.setText("jButton1");
        jPanel1.add(butFil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        labTen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTen1.setText("jLabel1");
        jPanel1.add(labTen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        labTen5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTen5.setText("jLabel1");
        jPanel1.add(labTen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        labTen3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTen3.setText("jLabel1");
        jPanel1.add(labTen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        butFil2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butFil2.setText("jButton1");
        jPanel1.add(butFil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        labTen2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTen2.setText("jLabel1");
        jPanel1.add(labTen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        labTen4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTen4.setText("jLabel1");
        jPanel1.add(labTen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        butFil3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butFil3.setText("jButton1");
        jPanel1.add(butFil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        butFil4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butFil4.setText("jButton1");
        jPanel1.add(butFil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        butFil5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        butFil5.setText("jButton1");
        jPanel1.add(butFil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("UNIVERSIDAD TÉCNICA DE AMBATO");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Integrantes: Diego Toapanta -Jadira Tubón -Silvia Villacrés");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PROBLEMA DE LOS FILOSOFOS COMENSALES");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Sistemas Operativos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       
        JButton filosofo[];
        filosofo = new JButton[5];
        filosofo[0] = butFil1;
        filosofo[1] = butFil2;
        filosofo[2] = butFil3;
        filosofo[3] = butFil4;
        filosofo[4] = butFil5;
       
        Filosofo com;
        
        JLabel tenedor[];
        tenedor = new JLabel[5];
        tenedor[0] = labTen1;
        tenedor[1] = labTen2;
        tenedor[2] = labTen3;
        tenedor[3] = labTen4;
        tenedor[4] = labTen5;
      
        int i, izq, der = 0;

        
        for (i = 0; i < 5; i++) {
          
            izq = i - 1;
           
            if (izq < 0) {
                izq = 4;
            }
            der = i;
         
            com = new Filosofo(i, tenedor[izq], tenedor[der], filosofo[i]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFil1;
    private javax.swing.JButton butFil2;
    private javax.swing.JButton butFil3;
    private javax.swing.JButton butFil4;
    private javax.swing.JButton butFil5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labTen1;
    private javax.swing.JLabel labTen2;
    private javax.swing.JLabel labTen3;
    private javax.swing.JLabel labTen4;
    private javax.swing.JLabel labTen5;
    // End of variables declaration//GEN-END:variables


    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagen/filosofos.png")).getImage();
            g.drawImage(imagen, 0, 0, 465, 361, this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
